import Head from "next/head";
import { useEffect, useState } from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import ProductServices from "@/services/products";
import ProductView from "@/components/views/products";

export default function Home() {
  const [products, setProducts] = useState([]);
  const session: any = useSession();

  useEffect(() => {
    const getData = async () => {
      try {
        const { data } = await ProductServices.getAllProducts();
        setProducts(data.data);
      } catch (error) {
        console.error("Failed to fetch products:", error);
      }
    };

    getData();
  }, []);
  return (
    <>
      <Head>
        <title>sidik store</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{products.length > 0 && <ProductView products={products} session={session} signIn={signIn} signOut={signOut} />}</main>
    </>
  );
}
